<a href="https://www.kaggle.com/code/jaskarandhillon1609/univariate-and-multivariate-linear-regression?scriptVersionId=210542630" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import linear_model

Linear Regression

In [2]:
df = pd.read_csv(r"/kaggle/input/home-prices/homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
new_df = df.drop('price', axis = 'columns')
new_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [4]:
price = df.price
price

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [5]:
reg = linear_model.LinearRegression()
reg.fit(new_df, price)

LinearRegression()

In [6]:
reg.predict([[4200]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([750924.65753425])

In [7]:
reg.intercept_

180616.43835616432

In [8]:
reg.coef_

array([135.78767123])

In [9]:
area_df = pd.read_csv(r"/kaggle/input/areas-dataset/areas.csv")
area_df.head()

area
0  1000
1  1500
2  2300
3  3540
4  4120

In [10]:
p = reg.predict(area_df)
p

array([ 316404.10958904,  384297.94520548,  492928.08219178,
        661304.79452055,  740061.64383562,  799808.21917808,
        926090.75342466,  650441.78082192,  825607.87671233,
        492928.08219178, 1402705.47945205, 1348390.4109589 ,
       1144708.90410959])

In [11]:
area_df['prices']=p
area_df


area        prices
0   1000  3.164041e+05
1   1500  3.842979e+05
2   2300  4.929281e+05
3   3540  6.613048e+05
4   4120  7.400616e+05
5   4560  7.998082e+05
6   5490  9.260908e+05
7   3460  6.504418e+05
8   4750  8.256079e+05
9   2300  4.929281e+05
10  9000  1.402705e+06
11  8600  1.348390e+06
12  7100  1.144709e+06

In [12]:
area_df.to_csv("prediction")

#Multivariate Linear Regression

In [13]:
df = pd.read_csv(r"/kaggle/input/home-prices/homepricesm.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
df.bedrooms.median()

4.0

In [15]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price', axis = 'columns'), df.price)

LinearRegression()

In [17]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
reg.intercept_

221323.00186540396

In [19]:
reg.predict([[3000, 3, 40]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [20]:
reg.predict([[2500, 4, 5]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])